calendall/calendall/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from profiles import urls as profile_urls
from calendars import urls as calendar_urls


urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^p/', include(profile_urls, namespace="profiles")),
    url(r'^c/', include(calendar_urls, namespace="calendars")),
    url(r'^admin/', include(admin.site.urls)),
)

# In production static stuff should be server by http server
# static handles automatically if the DEBUG is True
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

calendall/profiles/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^register$', views.CalendallUserCreate.as_view(),
        name="calendalluser_create"),

    url(r'^login$', views.Login.as_view(), name="login"),
    url(r'^logout$', views.Logout.as_view(), name="logout"),
    url(r'^validate/(?P<username>[a-zA-Z0-9\-]{1,30})/(?P<token>[a-f0-9]{32})$',
        views.Validate.as_view(), name="validate"),

    # Settings
    url(r'^settings/profile$', views.ProfileSettings.as_view(),
        name="profile_settings"),
    url(r'^settings/account$', views.AccountSettings.as_view(),
        name="account_settings"),

    # Password reset
    url(r'^ask/password/reset$', views.AskPasswordReset.as_view(),
        name="ask_password_reset"),
    url(r'^password/reset/(?P<username>[a-zA-Z0-9\-]{1,30})/(?P<token>[a-f0-9]{32})$',
        views.PasswordReset.as_view(),
        name="password_reset"),
)

calendall/templates/base.html
{# base.html #}
{% load i18n %}
{% load pipeline %}
{% load gravatar %}
{% load core_tags %}


<!DOCTYPE html>
<html>
  <head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Calendall</title>

    {% stylesheet 'base-libs' %}
    {% stylesheet 'custom-styles' %}

    {% javascript 'base-libs' %}
    {% javascript 'calendall-js' %}

    {% block head %}
    {% endblock head %}

  </head>
  <body>
  <div class="page-wrapper" data-sticky-wrap>
    <div class="ui main menu">
      <div class="ui container">
          <div class="title item">
              <i class="calendar icon"></i>
              Caledall
          </div>

          <div class="item">
            <div class="ui icon input">
              <input type="text" placeholder="{% trans "Search" %}">
              <i class="search icon"></i>
            </div>
          </div>

        <div class="right menu">

          {% if user.is_authenticated %}
              <a class="item" href="">
                <span class="right floated author">
                  <img class="ui avatar image" src="{% gravatar_url user.email 30 %}" /> {{ user.username }}
                </span>
              </a>
              <a class="item" href="{% url 'profiles:profile_settings'%}">
                <i class="settings icon"></i>
              </a>
              <a class="item" href="{% url "profiles:logout" %}">
                <i class="sign out icon"></i>
              </a>
          {% else %}
            <div class="item">
                {% url 'profiles:login' as login_url %}
                {% if request.path == login_url %}
                  <a class="ui blue button" href="{% url 'profiles:calendalluser_create' %}"> {% trans "Register" %} </a>
                {% else %}
                  <a class="ui button" href="{% url 'profiles:login' %}"> {% trans "Login" %} </a>
                {% endif %}
            </div>
          {% endif %}
        </div>
      </div>
  </div>

  <div class="ui page grid">
      {% if messages %}
      <div class="ui centered column grid">
          {% for message in messages %}
          <div claa="ui row">
          <div class="ui {{ message|message_css_class }} message">
              <i class="close icon"></i>
              <p>{{ message }}</p>
          </div>
          {% endfor %}
      </div>
      {% endif %}
        {% block content %}
        {% endblock content %}
      </div>
  </div>
</div> <!-- Page-wrapper -->

  <div data-sticky-footer class="footer">
    <div class="container">
      <div class="ui stackable divided relaxed grid">
        <div class="eight wide column">
          <h3 class="ui header">{% trans "Do you like Calendall?" %}</h3>
          <p>
            {% blocktrans %}
            Calendall is made in the free time of one person (for now), share it with your friends, family and everyone that want's free public cummunity driven calendars and support us! :)
            {% endblocktrans %}
          </p>
        </div>
        <div class="four wide column">
          <h5 class="ui header">{% trans "Contribute" %}</h5>
          <div class="ui link list">
            <a class="item" href="https://github.com/calendall" target="_blank">{% trans "Source code" %}</a>
            <a class="item" href="https://www.transifex.com/projects/p/calendall/" target="_blank">{% trans "Translation Hub" %}</a>
            <a class="item" href="https://github.com/calendall/issues" target="_blank">{% trans "Issue Tracker" %}</a>
          </div>
        </div>
        <div class="four wide column">
          <h5 class="ui header">{% trans "Calendall stuff" %}</h5>
          <div class="ui link list">
            <a class="item disabled" href="">{% trans "About us" %}</a>
            <a class="item disabled" href="">{% trans "Next steps" %}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</html>

calendall/templates/base_email.html
{# base_email.html #}
{# from: https://github.com/mailgun/transactional-email-templates #}
{% load pipeline %}
{% load i18n %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{% block title %}{% endblock title %}</title>
{% stylesheet 'email-libs' %}
</head>

<body>

<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" width="600">
            <div class="content">
                <table class="main" width="100%" cellpadding="0" cellspacing="0">

                </table>
                <div class="footer">
                    <table width="100%">
                    {% block content %}
                    {% endblock content %}
                        <tr>
                            <td class="aligncenter content-block">
                            <a href="">Calendall</a> {% trans "your favourite public calendar repository" %}
                            </td>
                        </tr>
                    </table>
                </div></div>
        </td>
        <td></td>
    </tr>
</table>

</body>
</html>