calendall/calendall/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from profiles import urls as profile_urls
from calendars import urls as calendar_urls


urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^p/', include(profile_urls, namespace="profiles")),
    url(r'^c/', include(calendar_urls, namespace="calendars")),
    url(r'^admin/', include(admin.site.urls)),
)

# In production static stuff should be server by http server
# static handles automatically if the DEBUG is True
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

calendall/profiles/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^register$', views.CalendallUserCreate.as_view(),
        name="calendalluser_create"),

    url(r'^login$', views.Login.as_view(), name="login"),
    url(r'^logout$', views.Logout.as_view(), name="logout"),
    url(r'^validate/(?P<username>[a-zA-Z0-9\-]{1,30})/(?P<token>[a-f0-9]{32})$',
        views.Validate.as_view(), name="validate"),

    # Settings
    url(r'^settings/profile$', views.ProfileSettings.as_view(),
        name="profile_settings"),
    url(r'^settings/account$', views.AccountSettings.as_view(),
        name="account_settings"),

    # Password reset
    url(r'^ask/password/reset$', views.AskPasswordReset.as_view(),
        name="ask_password_reset"),
    url(r'^password/reset/(?P<username>[a-zA-Z0-9\-]{1,30})/(?P<token>[a-f0-9]{32})$',
        views.PasswordReset.as_view(),
        name="password_reset"),
)

calendall/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
import pytz

from core.validators import validate_timezone

TIMEZONES = [(tz, tz) for tz in pytz.common_timezones]


@python_2_unicode_compatible
class CalendallUser(AbstractUser):

    timezone = models.CharField(_("User timezone"),
                                max_length=40,  # Max is 30, but 10 extra
                                choices=TIMEZONES,
                                default='UTC',
                                validators=[validate_timezone])
    # Tokens are uuid without slashes
    reset_token = models.CharField(_("reset token"),
                                   max_length=32,
                                   blank=True)
    reset_expiration = models.DateTimeField(_("reset token expiration"),
                                            null=True)

    validated = models.BooleanField(_("User account validated"), default=False)
    validation_token = models.CharField(_("User account validation token"),
                                        max_length=32,
                                        blank=True)
    url = models.URLField(_("User homepage"),
                          blank=True)

    location = models.CharField(_("User location"),
                                max_length=30,
                                blank=True)

    def __str__(self):
        return self.email

calendall/profiles/views.py
from datetime import timedelta
import logging
import uuid

from django.conf import settings
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.generic import CreateView, FormView, RedirectView
from django.views.generic.edit import UpdateView

from .models import CalendallUser
from .forms import (CalendallUserCreateForm, LoginForm, ProfileSettingsForm,
                    AccountSettingsForm, AskPasswordResetForm,
                    PasswordResetForm)

from core import utils
from core.views import LoginRequiredMixin

log = logging.getLogger(__name__)


class CalendallUserCreate(CreateView):
    model = CalendallUser
    fields = ['username', 'email', 'password']
    form_class = CalendallUserCreateForm
    template_name = "profiles/profiles_calendalluser_create.html"
    success_url = reverse_lazy('profiles:calendalluser_create')

    # Auto generate the validation token
    def form_valid(self, form):
        form.instance.validation_token = str(uuid.uuid4()).replace("-", "")
        return super().form_valid(form)

    def get_success_url(self):
        # Auto log in process:
        # Check password & user is ok (this isn't neccesary)
        user = authenticate(username=self.request.POST['username'],
                            password=self.request.POST['password'])
        if user is not None:
            if user.is_active:
                log.debug("Auto login '{0}'".format(user))
                login(self.request, user)

        # Send welcome email
        utils.send_templated_email("profiles/emails/profiles_email_welcome",
                                   self.get_context_data(),
                                   _("Welcome to Calendall"),
                                   settings.EMAIL_SUPPORT,
                                   (user.email,),
                                   self.request)

        # Send validation email
        utils.send_templated_email("profiles/emails/profiles_email_validation",
                                   self.get_context_data(),
                                   _("Validate your Calendall account"),
                                   settings.EMAIL_NOREPLY,
                                   (user.email,),
                                   self.request)

        return self.success_url

    @method_decorator(sensitive_post_parameters('password',
                                                'password_verification'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class Login(FormView):

    form_class = LoginForm
    template_name = "profiles/profiles_login.html"
    success_url = settings.LOGIN_REDIRECT_URL

    def form_valid(self, form):
        login(self.request, form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return super().form_valid(form)

    def get_success_url(self):
        # First check POST
        next_url = self.request.POST.get('next', None)

        if not next_url:
            next_url = self.request.GET.get('next', None)

        if next_url:
            self.success_url = next_url

        return self.success_url

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super().dispatch(request, *args, **kwargs)


class Logout(LoginRequiredMixin, RedirectView):

    url = settings.LOGIN_REDIRECT_URL

    def get(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, _("successfuly logged out"))
        return super().get(request, *args, **kwargs)


class Validate(RedirectView):
    url = settings.LOGIN_REDIRECT_URL

    def get(self, request, *args, **kwargs):
        error = True

        # Check if the values is correct
        try:
            u = CalendallUser.objects.get(username=self.kwargs['username'])

            if u.validated:
                log.debug("User '{0}' already validated".format(u))
                messages.info(request, _("Account already validated"))
                error = False

            elif u.validation_token == self.kwargs['token']:
                u.validated = True
                u.save()
                log.info("User '{0}' validated".format(u))
                messages.success(request, _("successfuly account validated"))
                error = False

        except CalendallUser.DoesNotExist:
            pass  # This will be error

        if error:
            log.debug(
                "Error validating user '{0}'".format(self.kwargs['username']))
            messages.error(request, _("Error validating the account"))

        return super().get(request, *args, **kwargs)


class ProfileSettings(LoginRequiredMixin, UpdateView):
    model = CalendallUser
    form_class = ProfileSettingsForm
    template_name = "profiles/profiles_profile_settings.html"
    success_url = reverse_lazy('profiles:profile_settings')

    # With this we don't need the pk in the url
    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        # Set the timezone of the user in the session
        self.request.session['user-tz'] = form.cleaned_data['timezone']
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, _("Profile updated"))
        return super().get_success_url()


class AccountSettings(LoginRequiredMixin, UpdateView):
    model = CalendallUser
    form_class = AccountSettingsForm
    template_name = "profiles/profiles_account_settings.html"
    success_url = reverse_lazy('profiles:account_settings')

    # we need request in the form
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        result = super().form_valid(form)
        # Don't logout the user (>= 1.7)
        update_session_auth_hash(self.request, self.request.user)
        return result

    # With this we don't need the pk in the url
    def get_object(self):
        return self.request.user

    def get_success_url(self):
        messages.success(self.request, _("Account updated"))
        return super().get_success_url()


class AskPasswordReset(FormView):

    form_class = AskPasswordResetForm
    template_name = "profiles/profiles_ask_password_reset.html"
    success_url = settings.LOGIN_REDIRECT_URL

    # Prepopulate the login if logged
    def get_initial(self):
        initial_data = super().get_initial()
        try:
            initial_data['email'] = self.request.user.email
        except AttributeError:
            pass  # anonymous user

        return initial_data

    def form_valid(self, form):

        # Get user
        context_data = self.get_context_data()
        u = CalendallUser.objects.get(
            email=form.cleaned_data['email'])

        # Create the token & date
        u.reset_token = str(uuid.uuid4()).replace("-", "")
        expiration_time = timezone.now()
        # Add expiration  time
        u.reset_expiration = expiration_time + timedelta(
            seconds=settings.PASSWORD_RESET_MAX_SECONDS)

        u.save()
        context_data['user'] = u

        # Send email
        utils.send_templated_email("profiles/emails/profiles_email_password_reset",
                                   context_data,
                                   _("Please reset your password"),
                                   settings.EMAIL_NOREPLY,
                                   (form.cleaned_data['email'],),
                                   self.request)

        messages.success(self.request, _("Email sent with the instructions"))

        return super().form_valid(form)


class PasswordReset(UpdateView):

    model = CalendallUser
    form_class = PasswordResetForm
    template_name = "profiles/profiles_password_reset.html"
    success_url = settings.LOGIN_REDIRECT_URL
    validation_error_url = reverse_lazy("profiles:ask_password_reset")

    def dispatch(self, request, *args, **kwargs):
        try:
            username = self.kwargs.get('username', "")
            token = self.kwargs.get('token', "")
            self.user = CalendallUser.objects.get(username=username)
            # First check the token is ok
            if token == self.user.reset_token and\
               self.user.reset_expiration >= timezone.now():
                return super().dispatch(request, *args, **kwargs)

        except CalendallUser.DoesNotExist:
            pass  # show error but not a clue about the user inexstence

        log.debug("Error resettings password for: {0}".format(username))
        messages.error(self.request, _("It looks like you clicked on an invalid password reset link or it expired. Please try again."))
        return redirect(self.validation_error_url)

    # With this we don't need the pk in the url
    def get_object(self):
        return self.user

    def form_valid(self, form):
        # Don't allow reset again
        self.user.reset_token = ""
        self.user.save()
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, _("Account updated"))
        return super().get_success_url()

calendall/templates/profiles/profiles_account_settings.html
{# profiles/profiles_calendaluser_create #}
{% extends "profiles/profiles_base.html" %}
{% load i18n %}
{% load gravatar %}
{% load core_tags %}


{% block content %}

{% if form.non_field_errors %}
<div class="ui centered column grid">
    <div claa="ui row">
    <div class="ui error message">
    <i class="close icon"></i>
        <div class="header">{% trans "Passord reset failed" %}</div>
        <!-- there is only one non field error -->
            <p class="form-error">{{ form.non_field_errors.0 }}</p>
    </div>
</div>
{% endif %}

<div class="ui fourteen wide centered column grid">

  <div class="ui row">
    <div class="four wide column">
      {% include "profiles/profiles_include_settings_menu.html" with current="account" %}
    </div>

    <div class="right floated left aligned twelve wide column">
      <div class="ui top attached segment">
        <div class="ui hidden divider"></div>
         <div class="left aligned row">
            <div class="ui top big attached label">
              {% trans "Password reset" %}
            </div>

            {# Form #}
            <div class="column">
              <form accept-charset="UTF-8" action="{% url 'profiles:account_settings' %}" class="ui fluid form settings" id="account-settings-form" method="post">

                  {% csrf_token %}
                  <!-------------- Old password ---------------------->
                  <div class="ui field input {% if form.old_password.errors %} error {% endif %}">
                    <label>{{ form.old_password.label }}</label>
                    <input id="{{ form.old_password.auto_id }}"
                            name="{{ form.old_password.name }}"
                            type="password"
                            value="">
                     {% if form.old_password.errors %}
                         <div class="ui red pointing left small label transition visible">
                           {% join_strings form.old_password.errors " and " ", " %}
                         </div>
                     {% endif %}
                 </div>

                  <!-------------- New password ---------------------->
                  <div class="ui field input {% if form.password.errors %} error {% endif %}">
                    <label>{{ form.password.label }}</label>
                    <input id="{{ form.password.auto_id }}"
                            name="{{ form.password.name }}"
                            type="password"
                            value="">
                     {% if form.password.errors %}
                         <div class="ui red pointing left small label transition visible">
                           {% join_strings form.password.errors " and " ", " %}
                         </div>
                     {% endif %}
                 </div>

                  <!-------------- New password validation---------------------->
                  <div class="ui field input {% if form.password_verification.errors %} error {% endif %}">
                    <label>{{ form.password_verification.label }}</label>
                    <input id="{{ form.password_verification.auto_id }}"
                            name="{{ form.password_verification.name }}"
                            type="password"
                            value="">
                     {% if form.password_verification.errors %}
                         <div class="ui red pointing left small label transition visible">
                           {% join_strings form.password_verification.errors " and " ", " %}
                         </div>
                     {% endif %}
                 </div>


                  <button type="submit" class="ui primary button" id="update_button">{% trans "Reset password" %}</button><a href="{% url "profiles:ask_password_reset" %}">{% trans "I forgot my password" %}</a>
                </form>
              </div>
          </div>
          </div>
  </div>
</div>
{% endblock content %}

calendall/templates/profiles/profiles_ask_password_reset.html
{# profiles/profiles_login.html #}
{% extends "profiles/profiles_base.html" %}
{% load i18n %}
{% load core_tags %}

{% block content %}

{% if form.non_field_errors %}
<div class="ui centered column grid">
    <div claa="ui row">
    <div class="ui error message">
    <i class="close icon"></i>
        <div class="header">{% trans "Login failed" %}</div>
        <!-- there is only one non field error -->
            <p class="form-error">{{ form.non_field_errors.0 }}</p>
    </div>
</div>
{% endif %}
<div class="ui six wide centered column grid">
    <div class="ui row">
        <div class="ui top attached segment sixteen wide column">
            <div class="ui hidden divider"></div>
            <form accept-charset="UTF-8" action="{% url 'profiles:ask_password_reset' %}" class="ui fluid form" id="ask-password-reset-form" method="post">

                {% csrf_token %}
                <!-------------- email field ---------------------->
                <div class="ui field input {% if form.email.errors %} error {% endif %}">
                    <label>{{ form.email.label }}</label>
                    <input id="{{ form.email.auto_id }}"
                            name="{{ form.email.name }}"
                            type="text"
                            value="{{ form.email.value|default:''}}">
                     {% if form.email.errors %}
                         <div class="ui red pointing small label transition visible">
                           {% join_strings form.email.errors " and " ", " %}
                         </div>
                     {% endif %}
                </div>

                <button type="submit" class="ui primary button" id="ask_password_reset_button">{% trans "Reset password" %}</button>
            </form>
        <div class="ui top attached big label">
            {% trans "Forgot password" %}
        </div>
        </div>
    </div>

</div>

{% endblock content %}

calendall/templates/profiles/profiles_base.html
{% extends "base.html" %}

calendall/templates/profiles/profiles_include_registration_step.html
{% load i18n %}



<div class="ui three steps">
  <div class="{% if step == 1 %} active {% elif step > 1 %} completed {% else %} disabled {% endif %} step">
    <i class="calendar icon"></i>
    <div class="content">
      <div class="title">{% trans "Register" %}</div>
      <div class="description">{% trans "Create a Calendall account" %}</div>
    </div>
  </div>
  <div class="{% if step == 2 %} active {% elif step > 2 %} completed {% else %} disabled {% endif %} step">
    <i class="upload icon"></i>
    <div class="content">
      <div class="title">{% trans "Import" %}</div>
      <div class="description">{% trans "Import your public calendars" %}</div>
    </div>
  </div>
  <div class="{% if step == 3 %} active {% elif step > 3 %} completed {% else %} disabled {% endif %} step">
    <i class="share alternate icon"></i>
    <div class="content">
      <div class="title">{% trans "Share" %}</div>
      <div class="description">{% trans "Share you calendars with others" %}</div>
    </div>
  </div>
</div>

calendall/templates/profiles/profiles_include_settings_menu.html
{% load i18n %}


<div class="ui vertical menu">
  <div class="big header item">
     {% trans "Personal settings" %}
  </div>

  <a class="{% if current == "profile" %}active{% endif %} item" href="{% url "profiles:profile_settings" %}">
    {% trans "Profile" %}
  </a>

  <a class="{% if current == "account" %}active{% endif %} item" href="{% url "profiles:account_settings" %}">
    {% trans "Account" %}
  </a>
</div>

calendall/templates/profiles/profiles_login.html
{# profiles/profiles_login.html #}
{% extends "profiles/profiles_base.html" %}
{% load i18n %}
{% load core_tags %}

{% block content %}

{% if form.non_field_errors %}
<div class="ui centered column grid">
    <div claa="ui row">
    <div class="ui error message">
    <i class="close icon"></i>
        <div class="header">{% trans "Login failed" %}</div>
        <!-- there is only one non field error -->
            <p class="form-error">{{ form.non_field_errors.0 }}</p>
    </div>
</div>
{% endif %}
<div class="ui six wide centered column grid">

    <div class="ui row">
        <div class="ui top attached segment sixteen wide column">
            <div class="ui hidden divider"></div>
            <form accept-charset="UTF-8" action="{% url 'profiles:login' %}" class="ui fluid form" id="signin-form" method="post">

                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.GET.next }}" />

                <!-------------- Username field ---------------------->
                <div class="ui field input {% if form.username.errors %} error {% endif %}">
                    <label>{{ form.username.label }}</label>
                    <input id="{{ form.username.auto_id }}"
                            name="{{ form.username.name }}"
                            type="text"
                            value="{{ form.username.value|default:''}}">
                     {% if form.username.errors %}
                         <div class="ui red pointing small label transition visible">
                           {% join_strings form.username.errors " and " ", " %}
                         </div>
                     {% endif %}
                </div>

                <!-------------- password field ---------------------->
                <div class="ui field input {% if form.password.errors %} error {% endif %}">
                    <label>{{ form.password.label }} <a href="{% url "profiles:ask_password_reset" %}">({% trans "forgot password" %})</a></label>
                    <input id="{{ form.password.auto_id }}"
                            name="{{ form.password.name }}"
                            type="password"
                            value="{{ form.password.value|default:''}}">
                     {% if form.password.errors %}
                         <div class="ui red pointing small label transition visible">
                           {% join_strings form.password.errors " and " ", " %}
                         </div>
                     {% endif %}
                </div>

                <button type="submit" class="ui primary button" id="login_button">{% trans "Login" %}</button>
            </form>
        <div class="ui top attached big label">
            {% trans "Login" %}
        </div>
        </div>
    </div>
</div>

{% endblock content %}

calendall/templates/profiles/profiles_password_reset.html
{# profiles/profiles_login.html #}
{% extends "profiles/profiles_base.html" %}
{% load i18n %}
{% load core_tags %}

{% block content %}

{% if form.non_field_errors %}
<div class="ui centered column grid">
    <div claa="ui row">
    <div class="ui error message">
    <i class="close icon"></i>
        <div class="header">{% trans "Password reset failed" %}</div>
        <!-- there is only one non field error -->
            <p class="form-error">{{ form.non_field_errors.0 }}</p>
    </div>
</div>
{% endif %}
<div class="ui six wide centered column grid">

    <div class="ui row">
        <div class="ui top attached segment sixteen wide column">
            <div class="ui hidden divider"></div>
              <form accept-charset="UTF-8" action="{% url 'profiles:password_reset'  object.username object.reset_token %}" class="ui fluid form settings" id="password-reset-form" method="post">

                  {% csrf_token %}
                  <!-------------- New password ---------------------->
                  <div class="ui field input {% if form.password.errors %} error {% endif %}">
                    <label>{{ form.password.label }}</label>
                    <input id="{{ form.password.auto_id }}"
                            name="{{ form.password.name }}"
                            type="password"
                            value="">
                     {% if form.password.errors %}
                         <div class="ui red pointing left small label transition visible">
                           {% join_strings form.password.errors " and " ", " %}
                         </div>
                     {% endif %}
                 </div>

                  <!-------------- New password validation---------------------->
                  <div class="ui field input {% if form.password_verification.errors %} error {% endif %}">
                    <label>{{ form.password_verification.label }}</label>
                    <input id="{{ form.password_verification.auto_id }}"
                            name="{{ form.password_verification.name }}"
                            type="password"
                            value="">
                     {% if form.password_verification.errors %}
                         <div class="ui red pointing left small label transition visible">
                           {% join_strings form.password_verification.errors " and " ", " %}
                         </div>
                     {% endif %}
                 </div>


                  <button type="submit" class="ui primary button" id="update_button">{% trans "Change password" %}</button>
                </form>
                <div class="ui top attached big label">
                    {% trans "Change your password" %}
                </div>
              </div>
        </div>
    </div>
</div>

{% endblock content %}